name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11 ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start Meilisearch
        uses: moy2010/meilisearch-github-action@0.1
        with:
          meilisearch-version: v0.25.2
          meilisearch-port: 42069
          meilisearch-api-key: masterKey
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/development.txt

      - name: Run Tests
        run: |
          python manage.py test
